"""code checkouts on connected repos

Revision ID: b8fb7c31aa01
Revises: 79724b8e8e6a
Create Date: 2026-10-02 14:40:06.238633
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b8fb7c31aa01"
down_revision: str | None = "79724b8e8e6a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("connected_repos", sa.Column("checkout_sha", sa.String(length=40), nullable=True))
    op.add_column(
        "connected_repos", sa.Column("checked_out_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "connected_repos", sa.Column("checkout_error", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("connected_repos", "checkout_error")
    op.drop_column("connected_repos", "checked_out_at")
    op.drop_column("connected_repos", "checkout_sha")
    # ### end Alembic commands ###
