"""coding runs

Revision ID: 20be969ff47a
Revises: 0112d9f1cc4d
Create Date: 2026-10-03 10:50:23.593400
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20be969ff47a"
down_revision: str | None = "0112d9f1cc4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coding_runs",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column("issue_key", sa.String(length=24), nullable=False),
        sa.Column(
            "agent",
            sa.Enum(
                "claude-code",
                "codex",
                name="codingagent",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "awaiting_approval",
                "rejected",
                "queued",
                "running",
                "pr_opened",
                "no_changes",
                "failed",
                "stopped",
                name="codingrunstatus",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("brief", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("repo_full_name", sa.String(length=200), nullable=False),
        sa.Column("base_branch", sa.String(length=200), nullable=False),
        sa.Column("base_sha", sa.String(length=40), nullable=True),
        sa.Column("branch", sa.String(length=200), nullable=True),
        sa.Column("commit_sha", sa.String(length=40), nullable=True),
        sa.Column("pr_number", sa.Integer(), nullable=True),
        sa.Column("pr_url", sa.String(length=300), nullable=True),
        sa.Column(
            "files_changed",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "events", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("error", sa.String(length=1000), nullable=True),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=4, asdecimal=False), nullable=True),
        sa.Column("requested_by_id", sa.Uuid(), nullable=True),
        sa.Column("decided_by_id", sa.Uuid(), nullable=True),
        sa.Column("decision_reason", sa.String(length=1000), nullable=True),
        sa.Column("stop_requested", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("review_run_id", sa.Uuid(), nullable=True),
        sa.Column("review_thread_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["decided_by_id"],
            ["users.id"],
            name=op.f("fk_coding_runs_decided_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
            name=op.f("fk_coding_runs_issue_id_issues"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_coding_runs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["users.id"],
            name=op.f("fk_coding_runs_requested_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_coding_runs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coding_runs")),
    )
    op.create_index(op.f("ix_coding_runs_issue_id"), "coding_runs", ["issue_id"], unique=False)
    op.create_index(op.f("ix_coding_runs_project_id"), "coding_runs", ["project_id"], unique=False)
    op.create_index(op.f("ix_coding_runs_status"), "coding_runs", ["status"], unique=False)
    op.create_index(
        op.f("ix_coding_runs_workspace_id"), "coding_runs", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_coding_runs_workspace_id"), table_name="coding_runs")
    op.drop_index(op.f("ix_coding_runs_status"), table_name="coding_runs")
    op.drop_index(op.f("ix_coding_runs_project_id"), table_name="coding_runs")
    op.drop_index(op.f("ix_coding_runs_issue_id"), table_name="coding_runs")
    op.drop_table("coding_runs")
    # ### end Alembic commands ###
