"""agent definitions

Revision ID: 4ec5ccb26b13
Revises: 4ce4902d9cf3
Create Date: 2026-09-29 21:04:52.059783
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4ec5ccb26b13"
down_revision: str | None = "4ce4902d9cf3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_definitions",
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("handle", sa.String(length=31), nullable=False),
        sa.Column("base", sa.String(length=31), nullable=True),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_agent_definitions_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_agent_definitions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_agent_definitions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_definitions")),
    )
    op.create_index(
        op.f("ix_agent_definitions_project_id"), "agent_definitions", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_definitions_workspace_id"),
        "agent_definitions",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "uq_agent_definitions_project_handle",
        "agent_definitions",
        ["project_id", "handle"],
        unique=True,
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.create_index(
        "uq_agent_definitions_workspace_handle",
        "agent_definitions",
        ["workspace_id", "handle"],
        unique=True,
        postgresql_where=sa.text("project_id IS NULL"),
    )
    op.create_table(
        "agent_definition_versions",
        sa.Column("definition_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.String(length=500), server_default="", nullable=False),
        sa.Column("author_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
            name=op.f("fk_agent_definition_versions_author_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["definition_id"],
            ["agent_definitions.id"],
            name=op.f("fk_agent_definition_versions_definition_id_agent_definitions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_agent_definition_versions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_definition_versions")),
        sa.UniqueConstraint(
            "definition_id",
            "version",
            name=op.f("uq_agent_definition_versions_definition_id_version"),
        ),
    )
    op.create_index(
        op.f("ix_agent_definition_versions_definition_id"),
        "agent_definition_versions",
        ["definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_definition_versions_workspace_id"),
        "agent_definition_versions",
        ["workspace_id"],
        unique=False,
    )
    op.add_column("agent_runs", sa.Column("agent_version", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_runs", "agent_version")
    op.drop_index(
        op.f("ix_agent_definition_versions_workspace_id"), table_name="agent_definition_versions"
    )
    op.drop_index(
        op.f("ix_agent_definition_versions_definition_id"), table_name="agent_definition_versions"
    )
    op.drop_table("agent_definition_versions")
    op.drop_index(
        "uq_agent_definitions_workspace_handle",
        table_name="agent_definitions",
        postgresql_where=sa.text("project_id IS NULL"),
    )
    op.drop_index(
        "uq_agent_definitions_project_handle",
        table_name="agent_definitions",
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_agent_definitions_workspace_id"), table_name="agent_definitions")
    op.drop_index(op.f("ix_agent_definitions_project_id"), table_name="agent_definitions")
    op.drop_table("agent_definitions")
    # ### end Alembic commands ###
