"""organisations' own model keys; automations without a daily cap

Revision ID: 098470f4cd91
Revises: 37628cdabdd7
Create Date: 2026-10-09 18:48:55.680068
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "098470f4cd91"
down_revision: str | None = "37628cdabdd7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace_model_keys",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("encrypted", sa.Text(), nullable=False),
        sa.Column("last4", sa.String(length=4), nullable=False),
        sa.Column("added_by_id", sa.Uuid(), nullable=True),
        sa.Column("limit_reached_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("limit_message", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["added_by_id"],
            ["users.id"],
            name=op.f("fk_workspace_model_keys_added_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_workspace_model_keys_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_model_keys")),
        sa.UniqueConstraint(
            "workspace_id", "provider", name=op.f("uq_workspace_model_keys_workspace_id_provider")
        ),
    )
    op.create_index(
        op.f("ix_workspace_model_keys_workspace_id"),
        "workspace_model_keys",
        ["workspace_id"],
        unique=False,
    )
    op.alter_column(
        "automations",
        "max_runs_per_day",
        existing_type=sa.INTEGER(),
        nullable=True,
        server_default=None,
        existing_server_default=sa.text("5"),
    )
    # Organisations run automations on their own keys: no daily cap unless an owner sets one.
    op.execute("UPDATE automations SET max_runs_per_day = NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE automations SET max_runs_per_day = 5 WHERE max_runs_per_day IS NULL")
    op.alter_column(
        "automations",
        "max_runs_per_day",
        existing_type=sa.INTEGER(),
        nullable=False,
        server_default=sa.text("5"),
    )
    op.drop_index(op.f("ix_workspace_model_keys_workspace_id"), table_name="workspace_model_keys")
    op.drop_table("workspace_model_keys")
    # ### end Alembic commands ###
