"""agent run mode

Revision ID: cee321a7923c
Revises: 12e63442a7a7
Create Date: 2026-10-01 09:33:10.079175
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cee321a7923c"
down_revision: str | None = "12e63442a7a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_runs", sa.Column("mode", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_runs", "mode")
    # ### end Alembic commands ###
