"""run agent and conversation model

Revision ID: f67d2a4525a9
Revises: 86579aa1f0e8
Create Date: 2026-09-29 11:18:47.897758
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f67d2a4525a9"
down_revision: str | None = "86579aa1f0e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_runs", sa.Column("agent", sa.String(length=32), nullable=True))
    op.add_column(
        "agent_runs", sa.Column("conversation_model", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_runs", "conversation_model")
    op.drop_column("agent_runs", "agent")
    # ### end Alembic commands ###
