"""agents act without approval

Revision ID: 3e9622ac41d6
Revises: a6c331da0f34
Create Date: 2026-10-09 16:26:18.565138
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3e9622ac41d6"
down_revision: str | None = "a6c331da0f34"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "automations", sa.Column("unattended", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column(
        "workspaces",
        sa.Column("unattended_paused", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspaces", "unattended_paused")
    op.drop_column("automations", "unattended")
    # ### end Alembic commands ###
