"""people's own agent preferences

Revision ID: 2dd0e843f850
Revises: a9142d1c93a7
Create Date: 2026-10-09 20:23:14.153638
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2dd0e843f850"
down_revision: str | None = "a9142d1c93a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("handle", sa.String(length=32), nullable=False),
        sa.Column("instructions", sa.String(length=2000), server_default="", nullable=False),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_agent_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_agent_preferences_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_preferences")),
        sa.UniqueConstraint(
            "workspace_id",
            "user_id",
            "handle",
            name=op.f("uq_agent_preferences_workspace_id_user_id_handle"),
        ),
    )
    op.create_index(
        op.f("ix_agent_preferences_user_id"), "agent_preferences", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_preferences_workspace_id"),
        "agent_preferences",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_preferences_workspace_id"), table_name="agent_preferences")
    op.drop_index(op.f("ix_agent_preferences_user_id"), table_name="agent_preferences")
    op.drop_table("agent_preferences")
    # ### end Alembic commands ###
