"""workspace member permissions

Revision ID: f965adb06bbf
Revises: bcef2a83d24c
Create Date: 2026-09-28 21:36:32.016816
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f965adb06bbf"
down_revision: str | None = "bcef2a83d24c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workspaces",
        sa.Column(
            "member_permissions",
            sa.ARRAY(sa.String(length=32)),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspaces", "member_permissions")
    # ### end Alembic commands ###
