"""projects and knowledge files

Revision ID: de4ede105141
Revises: 4616df62cf61
Create Date: 2026-09-26 21:31:00.398096
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "de4ede105141"
down_revision: str | None = "4616df62cf61"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("key", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), server_default="", nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "new_repo",
                "existing_repo",
                "docs_only",
                name="projectsource",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("repo_url", sa.String(length=500), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("knowledge_revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_projects_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_projects_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("workspace_id", "key", name=op.f("uq_projects_workspace_id_key")),
    )
    op.create_index(op.f("ix_projects_workspace_id"), "projects", ["workspace_id"], unique=False)
    op.create_table(
        "knowledge_files",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(length=300), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_knowledge_files_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_knowledge_files_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_files")),
        sa.UniqueConstraint("project_id", "path", name=op.f("uq_knowledge_files_project_id_path")),
    )
    op.create_index(
        "ix_knowledge_files_project_id_revision",
        "knowledge_files",
        ["project_id", "revision"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_files_workspace_id"), "knowledge_files", ["workspace_id"], unique=False
    )
    op.create_table(
        "knowledge_versions",
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "author_type",
            sa.Enum(
                "user",
                "agent",
                "system",
                name="authortype",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("agent", sa.String(length=32), nullable=True),
        sa.Column("instructed_by_id", sa.Uuid(), nullable=True),
        sa.Column("approved_by_id", sa.Uuid(), nullable=True),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["users.id"],
            name=op.f("fk_knowledge_versions_approved_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_knowledge_versions_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["knowledge_files.id"],
            name=op.f("fk_knowledge_versions_file_id_knowledge_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["instructed_by_id"],
            ["users.id"],
            name=op.f("fk_knowledge_versions_instructed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_knowledge_versions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_knowledge_versions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_versions")),
        sa.UniqueConstraint(
            "file_id", "version", name=op.f("uq_knowledge_versions_file_id_version")
        ),
    )
    op.create_index(
        op.f("ix_knowledge_versions_file_id"), "knowledge_versions", ["file_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_versions_project_id"), "knowledge_versions", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_versions_workspace_id"),
        "knowledge_versions",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_knowledge_versions_workspace_id"), table_name="knowledge_versions")
    op.drop_index(op.f("ix_knowledge_versions_project_id"), table_name="knowledge_versions")
    op.drop_index(op.f("ix_knowledge_versions_file_id"), table_name="knowledge_versions")
    op.drop_table("knowledge_versions")
    op.drop_index(op.f("ix_knowledge_files_workspace_id"), table_name="knowledge_files")
    op.drop_index("ix_knowledge_files_project_id_revision", table_name="knowledge_files")
    op.drop_table("knowledge_files")
    op.drop_index(op.f("ix_projects_workspace_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
