"""automations

Revision ID: 466a567e4122
Revises: 936fc339e7c1
Create Date: 2026-10-02 19:57:49.327829
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "466a567e4122"
down_revision: str | None = "936fc339e7c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automation_events",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event",
            sa.Enum(
                "issue.created",
                "issue.done",
                "document.changed",
                "changes.approved",
                "code.pushed",
                name="automationevent",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.String(length=300), nullable=False),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_automation_events_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_automation_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_events")),
    )
    op.create_index(
        op.f("ix_automation_events_project_id"), "automation_events", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_automation_events_workspace_id"),
        "automation_events",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "automations",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("agent", sa.String(length=32), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column(
            "events", postgresql.ARRAY(sa.String(length=32)), server_default="{}", nullable=False
        ),
        sa.Column("schedule_hour", sa.SmallInteger(), nullable=True),
        sa.Column("schedule_weekday", sa.SmallInteger(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("max_runs_per_day", sa.Integer(), server_default="5", nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("thread_id", sa.Uuid(), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_id", sa.Uuid(), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_automations_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_automations_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_automations_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automations")),
    )
    op.create_index(
        op.f("ix_automations_next_run_at"), "automations", ["next_run_at"], unique=False
    )
    op.create_index(op.f("ix_automations_project_id"), "automations", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_automations_workspace_id"), "automations", ["workspace_id"], unique=False
    )
    op.add_column("agent_runs", sa.Column("automation_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_agent_runs_automation_id"), "agent_runs", ["automation_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_agent_runs_automation_id_automations"),
        "agent_runs",
        "automations",
        ["automation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_agent_runs_automation_id_automations"), "agent_runs", type_="foreignkey"
    )
    op.drop_index(op.f("ix_agent_runs_automation_id"), table_name="agent_runs")
    op.drop_column("agent_runs", "automation_id")
    op.drop_index(op.f("ix_automations_workspace_id"), table_name="automations")
    op.drop_index(op.f("ix_automations_project_id"), table_name="automations")
    op.drop_index(op.f("ix_automations_next_run_at"), table_name="automations")
    op.drop_table("automations")
    op.drop_index(op.f("ix_automation_events_workspace_id"), table_name="automation_events")
    op.drop_index(op.f("ix_automation_events_project_id"), table_name="automation_events")
    op.drop_table("automation_events")
    # ### end Alembic commands ###
