"""email signups

Revision ID: bcef2a83d24c
Revises: a3c9e1f4b7d2
Create Date: 2026-09-28 20:41:02.403464
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "bcef2a83d24c"
down_revision: str | None = "a3c9e1f4b7d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_signups",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_signups")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_email_signups_token_hash")),
    )
    op.create_index(op.f("ix_email_signups_email"), "email_signups", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_signups_email"), table_name="email_signups")
    op.drop_table("email_signups")
    # ### end Alembic commands ###
