"""research notes on run outputs

Revision ID: 316382e0bb6b
Revises: 892e66c798ea
Create Date: 2026-10-01 12:42:26.609781
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "316382e0bb6b"
down_revision: str | None = "892e66c798ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_run_outputs", sa.Column("note", sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_run_outputs", "note")
    # ### end Alembic commands ###
