"""run usage breakdown, budgets, specialist model

Revision ID: 11cb1f3920d7
Revises: 013a2f78af7e
Create Date: 2026-09-28 23:30:52.343268
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "11cb1f3920d7"
down_revision: str | None = "013a2f78af7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_runs",
        sa.Column(
            "usage", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
    )
    op.add_column("agent_runs", sa.Column("token_budget", sa.Integer(), nullable=True))
    op.add_column("projects", sa.Column("specialist_model", sa.String(length=100), nullable=True))
    op.add_column("projects", sa.Column("token_budget", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "token_budget")
    op.drop_column("projects", "specialist_model")
    op.drop_column("agent_runs", "token_budget")
    op.drop_column("agent_runs", "usage")
    # ### end Alembic commands ###
