"""coding run screenshots

Revision ID: e7de79cc7435
Revises: 08ff69da2510
Create Date: 2026-10-10 17:33:10.941689
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e7de79cc7435"
down_revision: str | None = "08ff69da2510"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "coding_runs",
        sa.Column(
            "screenshots",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coding_runs", "screenshots")
    # ### end Alembic commands ###
