"""coding sessions

Revision ID: 75cbcf2c307a
Revises: 5901f57118a9
Create Date: 2026-10-10 19:55:02.861177
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "75cbcf2c307a"
down_revision: str | None = "5901f57118a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coding_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column(
            "agent",
            sa.Enum(
                "claude-code",
                "codex",
                name="codingagent",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "warm",
                "idle",
                "closed",
                name="codingsessionstate",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("claude_session", sa.Uuid(), nullable=False),
        sa.Column("transcript_key", sa.String(length=300), nullable=True),
        sa.Column(
            "cost_reported", sa.Numeric(precision=10, scale=4, asdecimal=False), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
            name=op.f("fk_coding_sessions_issue_id_issues"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_coding_sessions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_coding_sessions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coding_sessions")),
    )
    op.create_index(
        op.f("ix_coding_sessions_issue_id"), "coding_sessions", ["issue_id"], unique=False
    )
    op.create_index(
        op.f("ix_coding_sessions_project_id"), "coding_sessions", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_coding_sessions_workspace_id"), "coding_sessions", ["workspace_id"], unique=False
    )
    # A session for every existing run's session (no sandbox, no transcript yet): closed when its PR
    # was merged or closed, idle otherwise.
    op.execute(
        """
        INSERT INTO coding_sessions (id, workspace_id, project_id, issue_id, agent, state, claude_session,
                                     created_at, last_active_at, closed_at)
        SELECT DISTINCT ON (r.session_id) r.session_id, r.workspace_id, r.project_id, r.issue_id, r.agent,
               CASE WHEN r.pr_state IN ('merged', 'closed') THEN 'closed' ELSE 'idle' END,
               gen_random_uuid(), first.created_at,
               COALESCE(r.finished_at, r.started_at, r.created_at),
               CASE WHEN r.pr_state IN ('merged', 'closed') THEN COALESCE(r.finished_at, r.created_at) END
        FROM coding_runs r
        JOIN coding_runs first ON first.id = r.session_id
        ORDER BY r.session_id, r.turn DESC
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_coding_sessions_workspace_id"), table_name="coding_sessions")
    op.drop_index(op.f("ix_coding_sessions_project_id"), table_name="coding_sessions")
    op.drop_index(op.f("ix_coding_sessions_issue_id"), table_name="coding_sessions")
    op.drop_table("coding_sessions")
    # ### end Alembic commands ###
