"""teams, issue checklists, repeats, attachments, and stars

Revision ID: ecea5dc4905a
Revises: 654a6acf9e21
Create Date: 2026-10-08 21:28:54.709628
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ecea5dc4905a"
down_revision: str | None = "654a6acf9e21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("icon", sa.String(length=40), server_default="users", nullable=False),
        sa.Column("color", sa.String(length=7), server_default="#8A867E", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_teams_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("workspace_id", "name", name=op.f("uq_teams_workspace_id_name")),
    )
    op.create_index(op.f("ix_teams_workspace_id"), "teams", ["workspace_id"], unique=False)
    op.create_table(
        "team_members",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_team_members_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_team_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_team_members_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("team_id", "user_id", name=op.f("pk_team_members")),
        sa.UniqueConstraint(
            "workspace_id", "user_id", name=op.f("uq_team_members_workspace_id_user_id")
        ),
    )
    op.create_index(op.f("ix_team_members_team_id"), "team_members", ["team_id"], unique=False)
    op.create_index(
        op.f("ix_team_members_workspace_id"), "team_members", ["workspace_id"], unique=False
    )
    op.create_table(
        "team_projects",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_team_projects_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_team_projects_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_team_projects_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", name=op.f("pk_team_projects")),
    )
    op.create_index(op.f("ix_team_projects_team_id"), "team_projects", ["team_id"], unique=False)
    op.create_index(
        op.f("ix_team_projects_workspace_id"), "team_projects", ["workspace_id"], unique=False
    )
    op.create_table(
        "issue_attachments",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=600), nullable=False),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
            name=op.f("fk_issue_attachments_issue_id_issues"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_issue_attachments_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_issue_attachments_uploaded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_issue_attachments_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issue_attachments")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_issue_attachments_storage_key")),
    )
    op.create_index(
        op.f("ix_issue_attachments_issue_id"), "issue_attachments", ["issue_id"], unique=False
    )
    op.create_index(
        op.f("ix_issue_attachments_project_id"), "issue_attachments", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_issue_attachments_workspace_id"),
        "issue_attachments",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "issue_stars",
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
            name=op.f("fk_issue_stars_issue_id_issues"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_issue_stars_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_issue_stars_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issue_stars")),
        sa.UniqueConstraint("user_id", "issue_id", name=op.f("uq_issue_stars_user_id_issue_id")),
    )
    op.create_index(op.f("ix_issue_stars_issue_id"), "issue_stars", ["issue_id"], unique=False)
    op.create_index(op.f("ix_issue_stars_user_id"), "issue_stars", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_issue_stars_workspace_id"), "issue_stars", ["workspace_id"], unique=False
    )
    op.add_column(
        "issues",
        sa.Column(
            "checklist",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.add_column(
        "issues",
        sa.Column(
            "recurrence",
            sa.Enum(
                "daily",
                "weekly",
                "biweekly",
                "monthly",
                name="recurrence",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=True,
        ),
    )
    op.add_column("issues", sa.Column("repeated_as", sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("issues", "repeated_as")
    op.drop_column("issues", "recurrence")
    op.drop_column("issues", "checklist")
    op.drop_index(op.f("ix_issue_stars_workspace_id"), table_name="issue_stars")
    op.drop_index(op.f("ix_issue_stars_user_id"), table_name="issue_stars")
    op.drop_index(op.f("ix_issue_stars_issue_id"), table_name="issue_stars")
    op.drop_table("issue_stars")
    op.drop_index(op.f("ix_issue_attachments_workspace_id"), table_name="issue_attachments")
    op.drop_index(op.f("ix_issue_attachments_project_id"), table_name="issue_attachments")
    op.drop_index(op.f("ix_issue_attachments_issue_id"), table_name="issue_attachments")
    op.drop_table("issue_attachments")
    op.drop_index(op.f("ix_team_projects_workspace_id"), table_name="team_projects")
    op.drop_index(op.f("ix_team_projects_team_id"), table_name="team_projects")
    op.drop_table("team_projects")
    op.drop_index(op.f("ix_team_members_workspace_id"), table_name="team_members")
    op.drop_index(op.f("ix_team_members_team_id"), table_name="team_members")
    op.drop_table("team_members")
    op.drop_index(op.f("ix_teams_workspace_id"), table_name="teams")
    op.drop_table("teams")
    # ### end Alembic commands ###
