"""project status icon and color

Revision ID: 72dad5d930d0
Revises: 68f0b2a29705
Create Date: 2026-10-08 11:44:52.085253
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "72dad5d930d0"
down_revision: str | None = "68f0b2a29705"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "status",
            sa.Enum(
                "planning",
                "active",
                "on_hold",
                "completed",
                name="projectstatus",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="active",
            nullable=False,
        ),
    )
    op.add_column("projects", sa.Column("icon", sa.String(length=32), nullable=True))
    op.add_column(
        "projects",
        sa.Column(
            "color",
            sa.Enum(
                "indigo",
                "blue",
                "violet",
                "teal",
                "rose",
                "amber",
                "green",
                "slate",
                name="projectcolor",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "color")
    op.drop_column("projects", "icon")
    op.drop_column("projects", "status")
    # ### end Alembic commands ###
