"""agent run token usage

Revision ID: 68b02006152d
Revises: bb31c0fd2e5e
Create Date: 2026-09-28 12:57:19.709580
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "68b02006152d"
down_revision: str | None = "bb31c0fd2e5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_runs", sa.Column("model", sa.String(length=100), nullable=True))
    op.add_column(
        "agent_runs", sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "agent_runs", sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_runs", "output_tokens")
    op.drop_column("agent_runs", "input_tokens")
    op.drop_column("agent_runs", "model")
    # ### end Alembic commands ###
