"""issues

Revision ID: b540573e6112
Revises: 15383e7207ab
Create Date: 2026-09-27 00:26:15.615598
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b540573e6112"
down_revision: str | None = "15383e7207ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issues",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=24), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "epic",
                "story",
                "task",
                "bug",
                "spike",
                "sub-task",
                name="issuetype",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "todo",
                "in_progress",
                "blocked",
                "review",
                "done",
                name="issuestatus",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "low",
                "medium",
                "high",
                "urgent",
                name="priority",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("assignee_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "assignee_agent",
            sa.Enum(
                "coding-agent",
                "claude-code",
                "codex",
                name="agentassignee",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("reporter_user_id", sa.Uuid(), nullable=True),
        sa.Column("reporter_agent", sa.String(length=32), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("estimate", sa.Numeric(precision=8, scale=2, asdecimal=False), nullable=True),
        sa.Column("due", sa.Date(), nullable=True),
        sa.Column("scheduled", sa.DateTime(timezone=True), nullable=True),
        sa.Column("labels", sa.ARRAY(sa.String(length=64)), server_default="{}", nullable=False),
        sa.Column(
            "components", sa.ARRAY(sa.String(length=64)), server_default="{}", nullable=False
        ),
        sa.Column(
            "links", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("rank", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "assignee_user_id IS NULL OR assignee_agent IS NULL",
            name=op.f("ck_issues_one_assignee"),
        ),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id", name=op.f("ck_issues_not_own_parent")
        ),
        sa.CheckConstraint(
            "reporter_user_id IS NULL OR reporter_agent IS NULL",
            name=op.f("ck_issues_one_reporter"),
        ),
        sa.ForeignKeyConstraint(
            ["assignee_user_id"],
            ["users.id"],
            name=op.f("fk_issues_assignee_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["issues.id"],
            name=op.f("fk_issues_parent_id_issues"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_issues_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reporter_user_id"],
            ["users.id"],
            name=op.f("fk_issues_reporter_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_issues_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issues")),
        sa.UniqueConstraint("project_id", "number", name=op.f("uq_issues_project_id_number")),
    )
    op.create_index(
        op.f("ix_issues_assignee_user_id"), "issues", ["assignee_user_id"], unique=False
    )
    op.create_index("ix_issues_labels", "issues", ["labels"], unique=False, postgresql_using="gin")
    op.create_index(op.f("ix_issues_parent_id"), "issues", ["parent_id"], unique=False)
    op.create_index("ix_issues_project_id_rank", "issues", ["project_id", "rank"], unique=False)
    op.create_index("ix_issues_project_id_status", "issues", ["project_id", "status"], unique=False)
    op.create_index(op.f("ix_issues_workspace_id"), "issues", ["workspace_id"], unique=False)
    op.create_table(
        "issue_dependencies",
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column("depends_on_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "issue_id <> depends_on_id", name=op.f("ck_issue_dependencies_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["depends_on_id"],
            ["issues.id"],
            name=op.f("fk_issue_dependencies_depends_on_id_issues"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
            name=op.f("fk_issue_dependencies_issue_id_issues"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("issue_id", "depends_on_id", name=op.f("pk_issue_dependencies")),
    )
    op.create_index(
        op.f("ix_issue_dependencies_depends_on_id"),
        "issue_dependencies",
        ["depends_on_id"],
        unique=False,
    )
    op.create_table(
        "issue_events",
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "created",
                "updated",
                "commented",
                "claimed",
                name="issueeventkind",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("author_user_id", sa.Uuid(), nullable=True),
        sa.Column("author_agent", sa.String(length=32), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
            name=op.f("fk_issue_events_author_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
            name=op.f("fk_issue_events_issue_id_issues"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_issue_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issue_events")),
    )
    op.create_index(op.f("ix_issue_events_issue_id"), "issue_events", ["issue_id"], unique=False)
    op.create_index(
        op.f("ix_issue_events_workspace_id"), "issue_events", ["workspace_id"], unique=False
    )
    op.create_table(
        "issue_watchers",
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
            name=op.f("fk_issue_watchers_issue_id_issues"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_issue_watchers_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("issue_id", "user_id", name=op.f("pk_issue_watchers")),
    )
    op.add_column(
        "projects", sa.Column("next_issue_number", sa.Integer(), server_default="1", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "next_issue_number")
    op.drop_table("issue_watchers")
    op.drop_index(op.f("ix_issue_events_workspace_id"), table_name="issue_events")
    op.drop_index(op.f("ix_issue_events_issue_id"), table_name="issue_events")
    op.drop_table("issue_events")
    op.drop_index(op.f("ix_issue_dependencies_depends_on_id"), table_name="issue_dependencies")
    op.drop_table("issue_dependencies")
    op.drop_index(op.f("ix_issues_workspace_id"), table_name="issues")
    op.drop_index("ix_issues_project_id_status", table_name="issues")
    op.drop_index("ix_issues_project_id_rank", table_name="issues")
    op.drop_index(op.f("ix_issues_parent_id"), table_name="issues")
    op.drop_index("ix_issues_labels", table_name="issues", postgresql_using="gin")
    op.drop_index(op.f("ix_issues_assignee_user_id"), table_name="issues")
    op.drop_table("issues")
    # ### end Alembic commands ###
