"""personal model keys and default model

Revision ID: a9142d1c93a7
Revises: 098470f4cd91
Create Date: 2026-10-09 20:21:57.773996
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a9142d1c93a7"
down_revision: str | None = "098470f4cd91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_model_keys",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("encrypted", sa.Text(), nullable=False),
        sa.Column("last4", sa.String(length=4), nullable=False),
        sa.Column("limit_reached_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("limit_message", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_model_keys_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_model_keys")),
        sa.UniqueConstraint(
            "user_id", "provider", name=op.f("uq_user_model_keys_user_id_provider")
        ),
    )
    op.create_index(
        op.f("ix_user_model_keys_user_id"), "user_model_keys", ["user_id"], unique=False
    )
    op.add_column("users", sa.Column("default_model", sa.String(length=100), nullable=True))
    op.add_column(
        "workspaces",
        sa.Column("personal_keys", sa.Boolean(), server_default="true", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspaces", "personal_keys")
    op.drop_column("users", "default_model")
    op.drop_index(op.f("ix_user_model_keys_user_id"), table_name="user_model_keys")
    op.drop_table("user_model_keys")
    # ### end Alembic commands ###
