"""notification emails

Revision ID: 5ef76d56df55
Revises: 466a567e4122
Create Date: 2026-10-02 20:05:20.092441
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5ef76d56df55"
down_revision: str | None = "466a567e4122"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications", sa.Column("emailed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        "ix_notifications_unemailed",
        "notifications",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("emailed_at IS NULL"),
    )
    op.add_column(
        "users",
        sa.Column(
            "email_notifications",
            sa.String(length=16),
            server_default="immediately",
            nullable=False,
        ),
    )
    op.add_column("users", sa.Column("digest_sent_at", sa.DateTime(timezone=True), nullable=True))
    # A new kind: people hear when changes they asked for were decided.
    op.drop_constraint(op.f("ck_notifications_notificationkind"), "notifications", type_="check")
    op.create_check_constraint(
        op.f("ck_notifications_notificationkind"), "notifications",
        "kind IN ('approval', 'checkpoint', 'assigned', 'finding', 'mention', 'decided')",
    )
    # What was there before isn't emailed after the upgrade.
    op.execute("UPDATE notifications SET emailed_at = created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM notifications WHERE kind = 'decided'")
    op.drop_constraint(op.f("ck_notifications_notificationkind"), "notifications", type_="check")
    op.create_check_constraint(
        op.f("ck_notifications_notificationkind"), "notifications", "kind IN ('approval', 'checkpoint', 'assigned', 'finding', 'mention')"
    )
    op.drop_column("users", "digest_sent_at")
    op.drop_column("users", "email_notifications")
    op.drop_index(
        "ix_notifications_unemailed",
        table_name="notifications",
        postgresql_where=sa.text("emailed_at IS NULL"),
    )
    op.drop_column("notifications", "emailed_at")
    # ### end Alembic commands ###
