"""project stars, health and target date

Revision ID: 936fc339e7c1
Revises: b8fb7c31aa01
Create Date: 2026-10-02 18:37:38.432890
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "936fc339e7c1"
down_revision: str | None = "b8fb7c31aa01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_stars",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_stars_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_project_stars_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_project_stars_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_stars")),
        sa.UniqueConstraint(
            "user_id", "project_id", name=op.f("uq_project_stars_user_id_project_id")
        ),
    )
    op.create_index(
        op.f("ix_project_stars_project_id"), "project_stars", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_project_stars_user_id"), "project_stars", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_project_stars_workspace_id"), "project_stars", ["workspace_id"], unique=False
    )
    op.add_column(
        "projects",
        sa.Column(
            "health",
            sa.Enum(
                "on_track",
                "at_risk",
                "off_track",
                name="projecthealth",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=True,
        ),
    )
    op.add_column("projects", sa.Column("target_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "target_date")
    op.drop_column("projects", "health")
    op.drop_index(op.f("ix_project_stars_workspace_id"), table_name="project_stars")
    op.drop_index(op.f("ix_project_stars_user_id"), table_name="project_stars")
    op.drop_index(op.f("ix_project_stars_project_id"), table_name="project_stars")
    op.drop_table("project_stars")
    # ### end Alembic commands ###
