"""approvals say which agent asked

Revision ID: 37628cdabdd7
Revises: 3e9622ac41d6
Create Date: 2026-10-09 18:09:56.447124
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "37628cdabdd7"
down_revision: str | None = "3e9622ac41d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_approvals", sa.Column("agent", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_approvals", "agent")
    # ### end Alembic commands ###
