"""github installations and connected repos

Revision ID: 79724b8e8e6a
Revises: 6b65a1193c45
Create Date: 2026-10-02 09:04:42.880992
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "79724b8e8e6a"
down_revision: str | None = "6b65a1193c45"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_installations",
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("account_login", sa.String(length=100), nullable=False),
        sa.Column("account_type", sa.String(length=20), nullable=False),
        sa.Column("installed_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["installed_by_id"],
            ["users.id"],
            name=op.f("fk_github_installations_installed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_github_installations_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_github_installations")),
        sa.UniqueConstraint(
            "workspace_id",
            "installation_id",
            name=op.f("uq_github_installations_workspace_id_installation_id"),
        ),
    )
    op.create_index(
        op.f("ix_github_installations_installation_id"),
        "github_installations",
        ["installation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_github_installations_workspace_id"),
        "github_installations",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "connected_repos",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("installation_ref", sa.Uuid(), nullable=False),
        sa.Column("github_repo_id", sa.BigInteger(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("default_branch", sa.String(length=200), nullable=False),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("html_url", sa.String(length=300), nullable=False),
        sa.Column("connected_by_id", sa.Uuid(), nullable=True),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_push_sha", sa.String(length=40), nullable=True),
        sa.Column("last_push_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["connected_by_id"],
            ["users.id"],
            name=op.f("fk_connected_repos_connected_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["installation_ref"],
            ["github_installations.id"],
            name=op.f("fk_connected_repos_installation_ref_github_installations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_connected_repos_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_connected_repos_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connected_repos")),
        sa.UniqueConstraint("project_id", name=op.f("uq_connected_repos_project_id")),
        sa.UniqueConstraint(
            "workspace_id",
            "github_repo_id",
            name=op.f("uq_connected_repos_workspace_id_github_repo_id"),
        ),
    )
    op.create_index(
        op.f("ix_connected_repos_github_repo_id"),
        "connected_repos",
        ["github_repo_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_connected_repos_installation_ref"),
        "connected_repos",
        ["installation_ref"],
        unique=False,
    )
    op.create_index(
        op.f("ix_connected_repos_workspace_id"), "connected_repos", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_connected_repos_workspace_id"), table_name="connected_repos")
    op.drop_index(op.f("ix_connected_repos_installation_ref"), table_name="connected_repos")
    op.drop_index(op.f("ix_connected_repos_github_repo_id"), table_name="connected_repos")
    op.drop_table("connected_repos")
    op.drop_index(op.f("ix_github_installations_workspace_id"), table_name="github_installations")
    op.drop_index(
        op.f("ix_github_installations_installation_id"), table_name="github_installations"
    )
    op.drop_table("github_installations")
    # ### end Alembic commands ###
