"""document conversion status

Revision ID: 6c5da14a4550
Revises: 68b02006152d
Create Date: 2026-09-28 18:10:29.988505
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6c5da14a4550"
down_revision: str | None = "68b02006152d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "status",
            sa.Enum(
                "converting",
                "ready",
                "failed",
                name="documentstatus",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="ready",
            nullable=False,
        ),
    )
    op.add_column("documents", sa.Column("error", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "error")
    op.drop_column("documents", "status")
    # ### end Alembic commands ###
