"""coding sessions

Revision ID: 68f0b2a29705
Revises: 20be969ff47a
Create Date: 2026-10-03 12:45:31.267791
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "68f0b2a29705"
down_revision: str | None = "20be969ff47a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Each existing run is a session of its own (its first turn).
    op.add_column("coding_runs", sa.Column("session_id", sa.Uuid(), nullable=True))
    op.execute("UPDATE coding_runs SET session_id = id")
    op.alter_column("coding_runs", "session_id", nullable=False)
    op.add_column(
        "coding_runs", sa.Column("turn", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column(
        "coding_runs",
        sa.Column(
            "origin",
            sa.Enum(
                "start",
                "assigned",
                "follow_up",
                name="codingorigin",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="start",
            nullable=False,
        ),
    )
    op.add_column(
        "coding_runs",
        sa.Column(
            "pr_state",
            sa.Enum(
                "open",
                "merged",
                "closed",
                name="prstate",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=True,
        ),
    )
    op.create_index(op.f("ix_coding_runs_session_id"), "coding_runs", ["session_id"], unique=False)
    op.add_column("notifications", sa.Column("coding_run_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_notifications_coding_run_id"), "notifications", ["coding_run_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_notifications_coding_run_id_coding_runs"),
        "notifications",
        "coding_runs",
        ["coding_run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_notifications_coding_run_id_coding_runs"), "notifications", type_="foreignkey"
    )
    op.drop_index(op.f("ix_notifications_coding_run_id"), table_name="notifications")
    op.drop_column("notifications", "coding_run_id")
    op.drop_index(op.f("ix_coding_runs_session_id"), table_name="coding_runs")
    op.drop_column("coding_runs", "pr_state")
    op.drop_column("coding_runs", "origin")
    op.drop_column("coding_runs", "turn")
    op.drop_column("coding_runs", "session_id")
    # ### end Alembic commands ###
