"""agent run outputs

Revision ID: 3b73b89797fa
Revises: 4ec5ccb26b13
Create Date: 2026-09-29 21:25:44.759958
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3b73b89797fa"
down_revision: str | None = "4ec5ccb26b13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_run_outputs",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("agent", sa.String(length=32), nullable=False),
        sa.Column("schema", sa.String(length=32), nullable=False),
        sa.Column("items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_agent_run_outputs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_agent_run_outputs_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_agent_run_outputs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_run_outputs")),
    )
    op.create_index(
        op.f("ix_agent_run_outputs_project_id"), "agent_run_outputs", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_run_outputs_run_id"), "agent_run_outputs", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_run_outputs_workspace_id"),
        "agent_run_outputs",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_run_outputs_workspace_id"), table_name="agent_run_outputs")
    op.drop_index(op.f("ix_agent_run_outputs_run_id"), table_name="agent_run_outputs")
    op.drop_index(op.f("ix_agent_run_outputs_project_id"), table_name="agent_run_outputs")
    op.drop_table("agent_run_outputs")
    # ### end Alembic commands ###
