"""research sources and web pages

Revision ID: 892e66c798ea
Revises: cee321a7923c
Create Date: 2026-10-01 12:00:11.854848
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "892e66c798ea"
down_revision: str | None = "cee321a7923c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "web_pages",
        sa.Column("url_key", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("final_url", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("markdown", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("published", sa.String(length=40), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("via", sa.String(length=8), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_web_pages_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_web_pages")),
        sa.UniqueConstraint(
            "workspace_id", "url_key", name=op.f("uq_web_pages_workspace_id_url_key")
        ),
    )
    op.create_index(op.f("ix_web_pages_fetched_at"), "web_pages", ["fetched_at"], unique=False)
    op.create_index(op.f("ix_web_pages_workspace_id"), "web_pages", ["workspace_id"], unique=False)
    op.create_table(
        "research_sources",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("tier", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=False),
        sa.Column("published", sa.String(length=40), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("via", sa.String(length=8), nullable=True),
        sa.Column(
            "flagged", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_research_sources_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_research_sources_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_research_sources_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_sources")),
        sa.UniqueConstraint("run_id", "number", name=op.f("uq_research_sources_run_id_number")),
    )
    op.create_index(
        op.f("ix_research_sources_project_id"), "research_sources", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_research_sources_run_id"), "research_sources", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_research_sources_workspace_id"), "research_sources", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_research_sources_workspace_id"), table_name="research_sources")
    op.drop_index(op.f("ix_research_sources_run_id"), table_name="research_sources")
    op.drop_index(op.f("ix_research_sources_project_id"), table_name="research_sources")
    op.drop_table("research_sources")
    op.drop_index(op.f("ix_web_pages_workspace_id"), table_name="web_pages")
    op.drop_index(op.f("ix_web_pages_fetched_at"), table_name="web_pages")
    op.drop_table("web_pages")
    # ### end Alembic commands ###
