"""coding session title pin archive

Revision ID: 38c0a99a03ce
Revises: 75cbcf2c307a
Create Date: 2026-10-10 20:16:05.534791
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "38c0a99a03ce"
down_revision: str | None = "75cbcf2c307a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("coding_sessions", sa.Column("title", sa.String(length=200), nullable=True))
    op.add_column(
        "coding_sessions", sa.Column("pinned_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "coding_sessions", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coding_sessions", "archived_at")
    op.drop_column("coding_sessions", "pinned_at")
    op.drop_column("coding_sessions", "title")
    # ### end Alembic commands ###
