"""archive, comment edits and reactions, keep audit when a project goes

Revision ID: a6c331da0f34
Revises: ecea5dc4905a
Create Date: 2026-10-08 22:25:14.824348
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a6c331da0f34"
down_revision: str | None = "ecea5dc4905a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_audit_events_project_id_projects"), "audit_events", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_audit_events_project_id_projects"),
        "audit_events",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("issue_events", sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "issue_events",
        sa.Column(
            "reactions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column("issues", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("projects", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "archived_at")
    op.drop_column("issues", "archived_at")
    op.drop_column("issue_events", "reactions")
    op.drop_column("issue_events", "edited_at")
    op.drop_constraint(
        op.f("fk_audit_events_project_id_projects"), "audit_events", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_audit_events_project_id_projects"),
        "audit_events",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
