"""search index: knowledge chunks with pgvector

Revision ID: 86579aa1f0e8
Revises: 11cb1f3920d7
Create Date: 2026-09-28 23:52:16.584442
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "86579aa1f0e8"
down_revision: str | None = "11cb1f3920d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector: in the pgvector/pgvector image locally and in CI; production needs a Postgres
    # host that offers it (Neon, Supabase, RDS, Cloud SQL do).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_chunks",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "document",
                "issue",
                name="chunksource",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("file_id", sa.Uuid(), nullable=True),
        sa.Column("issue_id", sa.Uuid(), nullable=True),
        sa.Column("ref", sa.String(length=300), nullable=False),
        sa.Column("heading", sa.String(length=300), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('english', coalesce(ref, '') || ' ' || coalesce(heading, '')), 'A') || to_tsvector('english', content)",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.Column("embedding_model", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["knowledge_files.id"],
            name=op.f("fk_knowledge_chunks_file_id_knowledge_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
            name=op.f("fk_knowledge_chunks_issue_id_issues"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_knowledge_chunks_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_knowledge_chunks_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_chunks")),
    )
    op.create_index(
        "ix_knowledge_chunks_embedding",
        "knowledge_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_knowledge_chunks_file_id"), "knowledge_chunks", ["file_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_chunks_issue_id"), "knowledge_chunks", ["issue_id"], unique=False
    )
    op.create_index(
        "ix_knowledge_chunks_project_id_source",
        "knowledge_chunks",
        ["project_id", "source"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_chunks_tsv", "knowledge_chunks", ["tsv"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        op.f("ix_knowledge_chunks_workspace_id"), "knowledge_chunks", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_knowledge_chunks_workspace_id"), table_name="knowledge_chunks")
    op.drop_index("ix_knowledge_chunks_tsv", table_name="knowledge_chunks", postgresql_using="gin")
    op.drop_index("ix_knowledge_chunks_project_id_source", table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_issue_id"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_file_id"), table_name="knowledge_chunks")
    op.drop_index(
        "ix_knowledge_chunks_embedding",
        table_name="knowledge_chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("knowledge_chunks")
    # ### end Alembic commands ###
    # The vector extension stays: dropping it could break anything else that uses it.
