"""knowledge descriptions

Revision ID: 895f836c1864
Revises: f965adb06bbf
Create Date: 2026-09-28 22:00:40.277521
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "895f836c1864"
down_revision: str | None = "f965adb06bbf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("knowledge_files", sa.Column("title", sa.String(length=200), nullable=True))
    op.add_column("knowledge_files", sa.Column("summary", sa.String(length=300), nullable=True))
    op.add_column(
        "knowledge_files",
        sa.Column(
            "outline", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
    )
    op.add_column("knowledge_files", sa.Column("described_version", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("knowledge_files", "described_version")
    op.drop_column("knowledge_files", "outline")
    op.drop_column("knowledge_files", "summary")
    op.drop_column("knowledge_files", "title")
    # ### end Alembic commands ###
