"""coding run events

Revision ID: 5901f57118a9
Revises: e7de79cc7435
Create Date: 2026-10-10 17:48:07.801177
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5901f57118a9"
down_revision: str | None = "e7de79cc7435"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coding_events",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["coding_runs.id"],
            name=op.f("fk_coding_events_run_id_coding_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_coding_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coding_events")),
        sa.UniqueConstraint("run_id", "seq", name=op.f("uq_coding_events_run_id_seq")),
    )
    op.create_index(op.f("ix_coding_events_run_id"), "coding_events", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_coding_events_session_id"), "coding_events", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_coding_events_workspace_id"), "coding_events", ["workspace_id"], unique=False
    )
    op.add_column(
        "coding_runs", sa.Column("event_count", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###
    # The events runs already have (their latest, up to 300) move into the table, in order.
    op.execute(
        """
        INSERT INTO coding_events (id, workspace_id, run_id, session_id, seq, at, kind, text)
        SELECT gen_random_uuid(), r.workspace_id, r.id, r.session_id, e.ord - 1,
               COALESCE((e.value->>'at')::timestamptz, r.created_at),
               COALESCE(e.value->>'kind', 'step'), COALESCE(e.value->>'text', '')
        FROM coding_runs r, jsonb_array_elements(r.events) WITH ORDINALITY AS e(value, ord)
        """
    )
    op.execute("UPDATE coding_runs SET event_count = jsonb_array_length(events)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coding_runs", "event_count")
    op.drop_index(op.f("ix_coding_events_workspace_id"), table_name="coding_events")
    op.drop_index(op.f("ix_coding_events_session_id"), table_name="coding_events")
    op.drop_index(op.f("ix_coding_events_run_id"), table_name="coding_events")
    op.drop_table("coding_events")
    # ### end Alembic commands ###
