"""agent run titles

Revision ID: c1157ab0a54a
Revises: 965cf06fa077
Create Date: 2026-09-27 19:37:38.837481
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c1157ab0a54a"
down_revision: str | None = "965cf06fa077"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_runs", sa.Column("title", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_runs", "title")
    # ### end Alembic commands ###
