"""run cache and call counts

Revision ID: 013a2f78af7e
Revises: 895f836c1864
Create Date: 2026-09-28 22:45:19.765794
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "013a2f78af7e"
down_revision: str | None = "895f836c1864"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_runs",
        sa.Column("cached_input_tokens", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "agent_runs", sa.Column("model_calls", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_runs", "model_calls")
    op.drop_column("agent_runs", "cached_input_tokens")
    # ### end Alembic commands ###
