"""runs stopped at a model limit can continue

Revision ID: 08ff69da2510
Revises: 2dd0e843f850
Create Date: 2026-10-09 20:25:01.018004
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "08ff69da2510"
down_revision: str | None = "2dd0e843f850"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_runs", sa.Column("error_kind", sa.String(length=32), nullable=True))
    op.add_column("agent_runs", sa.Column("resumes_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "agent_runs",
        sa.Column("continue_at_reset", sa.Boolean(), server_default="false", nullable=False),
    )
    # A new kind: a run stopped at its model's limit, ready to continue.
    op.drop_constraint(op.f("ck_notifications_notificationkind"), "notifications", type_="check")
    op.create_check_constraint(
        op.f("ck_notifications_notificationkind"), "notifications",
        "kind IN ('approval', 'checkpoint', 'assigned', 'finding', 'mention', 'decided', 'watching', 'limit')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM notifications WHERE kind = 'limit'")
    op.drop_constraint(op.f("ck_notifications_notificationkind"), "notifications", type_="check")
    op.create_check_constraint(
        op.f("ck_notifications_notificationkind"), "notifications",
        "kind IN ('approval', 'checkpoint', 'assigned', 'finding', 'mention', 'decided', 'watching')",
    )
    op.drop_column("agent_runs", "continue_at_reset")
    op.drop_column("agent_runs", "resumes_at")
    op.drop_column("agent_runs", "error_kind")
    # ### end Alembic commands ###
