"""profile title and photo

Revision ID: 7fb098d009fc
Revises: 316382e0bb6b
Create Date: 2026-10-01 21:56:13.800628
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7fb098d009fc"
down_revision: str | None = "316382e0bb6b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_avatars",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_avatars_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_avatars")),
    )
    op.add_column("users", sa.Column("title", sa.String(length=100), nullable=True))
    op.add_column(
        "users", sa.Column("avatar_updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_updated_at")
    op.drop_column("users", "title")
    op.drop_table("user_avatars")
    # ### end Alembic commands ###
