"""Hand-off to coding tools (Claude Code, Codex, anything that speaks MCP).

Two parts, neither of which ever lands in git:

1. MCP registration (the main channel). `dotrix mcp` serves the project's
   `.dotrix/` knowledge and task tools. It's registered in each tool's own
   user-level config: Claude Code's local scope (~/.claude.json) and Codex's
   ~/.codex/config.toml. Nothing is written into the repo (not `.mcp.json`,
   not `.codex/config.toml`), so teammates' clones stay clean.

2. Instruction files. Claude Code reads CLAUDE.md and Codex reads AGENTS.md at
   session start. dotrix writes a short managed section telling them the
   knowledge lives behind the MCP server and when to use it. These files are
   git-excluded (see gitguard.py). If the repo already tracks its own
   AGENTS.md/CLAUDE.md, dotrix leaves it alone: writing into a tracked file
   would put the section into the next commit. The MCP server's own
   instructions carry the same guidance, so nothing is lost.

Behaviour the section asks for: work on a dotrix task only when the user says
so. Tools never auto-claim at session start.
"""
from __future__ import annotations

import re
import shlex
import shutil
import subprocess
from pathlib import Path

from .config import ProjectConfig
from .gitguard import is_tracked, protect

START = "<!-- dotrix:start -->"   # gitguard.MARKER must match this prefix
END = "<!-- dotrix:end -->"


def _slug(name: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return s or "project"


def mcp_server_name(config: ProjectConfig) -> str:
    # Codex config is global, so the name must be unique per project.
    return f"dotrix-{_slug(config.name)}"


def mcp_commands(config: ProjectConfig, *, claude_assignee: str = "claude-code",
                 codex_assignee: str = "codex") -> dict[str, list[str]]:
    root = str(Path(config.root_dir).resolve())
    name = mcp_server_name(config)
    serve = ["dotrix", "mcp", "--project", root]
    return {
        # --scope local: stored in ~/.claude.json for this project only, not .mcp.json
        "claude": ["claude", "mcp", "add", "--transport", "stdio", "--scope", "local",
                   name, "--", *serve, "--assignee", claude_assignee],
        "codex": ["codex", "mcp", "add", name, "--", *serve, "--assignee", codex_assignee],
    }


def _section(config: ProjectConfig, assignee: str) -> str:
    name = mcp_server_name(config)
    return f"""{START}
## Project knowledge and tasks (generated by dotrix; not committed)

This project's requirements, architecture, decisions (ADRs), research, and task
board are NOT in the repo. Read them through the `{name}` MCP server
(tools: project_overview, list_docs, read_doc, search_docs, list_tasks, get_task).
If that server isn't connected, run `dotrix handoff install` and restart.

- Before designing or changing code, check the relevant requirements, architecture
  notes, and ADRs. Follow recorded decisions; if the code must contradict one, stop
  and ask.
- Work on a dotrix task only when the user tells you to. Then `claim_task`, build
  it, log progress with `comment_task`, use `set_task_blocked` if stuck, and finish
  with `submit_for_review` (summary: what changed, files, how to test). Never mark
  a task done yourself. You act as `{assignee}`.
- You cannot edit project knowledge; propose changes to the user instead.
- Never copy `.dotrix/` content into the repo, and never commit `.dotrix/`,
  AGENTS.md, or CLAUDE.md.

CLI fallback without MCP: `dotrix task show <id>`, `dotrix task comment <id> "..." --author {assignee}`,
`dotrix task done <id> --review --note "..." --author {assignee}`.
{END}
"""


def _upsert(path: Path, block: str) -> str:
    if not path.exists():
        path.write_text(block)
        return "created"
    text = path.read_text()
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END) + r"\n?", re.S)
    if pattern.search(text):
        path.write_text(pattern.sub(lambda _: block, text, count=1))
        return "updated"
    path.write_text(text.rstrip() + "\n\n" + block)
    return "appended"


def install_handoff(config: ProjectConfig, *, codex_assignee: str = "codex",
                    claude_assignee: str = "claude-code",
                    register_mcp: bool = False) -> dict[str, str]:
    """Write the managed sections (only into untracked files) and, if asked,
    register the MCP server with whichever of `claude` / `codex` is installed."""
    protect(config.root_dir, config.dotrix_dir)  # ensure excludes/hook first
    root = Path(config.root_dir)
    report: dict[str, str] = {}
    for fname, who in (("AGENTS.md", codex_assignee), ("CLAUDE.md", claude_assignee)):
        if is_tracked(config.root_dir, fname):
            report[fname] = ("skipped: tracked by git, left untouched "
                             "(the MCP server's instructions cover it)")
        else:
            report[fname] = _upsert(root / fname, _section(config, who))

    cmds = mcp_commands(config, claude_assignee=claude_assignee, codex_assignee=codex_assignee)
    for tool, cmd in cmds.items():
        key = f"mcp:{tool}"
        if not register_mcp:
            report[key] = "run: " + shlex.join(cmd)
        elif shutil.which(cmd[0]) is None:
            report[key] = f"{cmd[0]} not installed; later run: " + shlex.join(cmd)
        else:
            r = subprocess.run(cmd, capture_output=True, text=True)
            report[key] = "registered" if r.returncode == 0 else \
                f"failed ({(r.stderr or r.stdout).strip()[:200]}); run: " + shlex.join(cmd)
    return report
